### ISSUE TITLE
Doesn't work when selectable model doesn't descend directly from Backbone.Model

### ISSUE THREAD

**Issue by allforabit** [hashchange/backbone.select#10]
I'm using another library Supermodel.js and this provides it's own module that inherits from Backbone.Model. The check for the model type: model instanceof Backbone.Model only checks the parent and not the full hierarchy. I'm wondering if there'd be another way to check the full hierarchy to see if the model descends from Backbone.Model. Another solution would be to make supermodel work as a mixin similarly to backbone.select.

**Comment by hashchange** [comment]
Well, `instanceOf` [_does_ check](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof) the prototype chain. Nesting is not an issue. I don't know about Supermodel.js but it probably breaks inheritance somehow.

I'll close this, it doesn't seem to be a Backbone.Select issue. Please feel free to reopen it if you think I have overlooked something.
