### ISSUE TITLE
Selected model not deselected when Select.Many is reset with new models

### ISSUE THREAD

**Issue by bnjmnhndrsn** [hashchange/backbone.select#12]
If a model in a Collection.Select.Many is selected and then the collection is reset with new models, the `collection.selected` property still returns the first model even though it is no longer in the collection. Furthermore, if `deselectAll` is called on the collection, the model remains in the `collection.selected` property and is not selected.

Here's a fiddle illustrating the problem: https://jsfiddle.net/57pap602/1/.

**Comment by hashchange** [comment]
Thanks for your report, and for your patience. This is essentially a "documentation bug": the relevant listeners are not active unless [model sharing mode][1] is enabled. Set that flag when you instantiate the collection, and it [works just fine][2].

I'll have a look later on if I can change things around a bit, or leave them as they are and just clarify the behaviour in the documentation. Please don't hold your breath, though, unfortunately it will take a while until I get to work on Backbone.Select. 

[1]: https://github.com/hashchange/backbone.select/tree/1.5.3#sharing-models-among-collections
[2]: http://jsbin.com/dipitax/6/edit?js,console

**Comment by hashchange** [comment]
I've had another look today, and I no longer think that a clarification in the readme is enough of a fix. There shouldn't be an option which enables correct behaviour on `reset` (or `add`, or `remove`). It should just work.

So I'll publish a version 2 in a while, and that version will no longer have an `enableModelSharing` option. It will be on by default, and can't be switched off. 

There are a couple of drawbacks: people have to call `close()` when removing a collection, and shouldn't really use the `silent` option with `add()`, `remove()` or `reset()`. (With the `silent` option on, the behaviour is the same as with model sharing disabled, so essentially there is no change in that regard.)

But I think these drawbacks are worth it, in exchange for intuitive and correct behaviour with basic Backbone operations.

**Comment by hashchange** [comment]
Is no longer an issue in Backbone 2.0.0.
