### ISSUE TITLE
Not Working With Underscore 1.7 or Lodash 1+

### ISSUE THREAD

**Issue by rfastturnlow** [hashchange/backbone.select#4]
When I was experimenting with substituting lodash for backbone, this mixin stopped working.  Looking closer, the extend method in the latest underscore and most lodash versions only copies an objects own properties.  Version <=1.6 of underscore will include properties defined on the prototype so the following method was working there: 
    _.extend( hostObject, new Backbone.Select.One() );

Since I didn't see a need for the instance, I just made the mixins plain objects and passed those to the extend methods like so.
    _.extend( hostObject, SelectOneMixin );

I'll attach a PR shortly.  Other than that, thanks for this project.  It's been very helpful.

Cheers!

**Comment by rfastturnlow** [comment]
The adjustment I made is in PR #5.  Thanks again!

**Comment by hashchange** [comment]
Your PR has been sitting here _way too long_. Sorry for that! It works great, and in fact I should have done it like that from the outset. 

I have merged your PR now. Thanks a lot for your contribution!
